---

- name: "Installing weblounge rpm repository"
  template: >
        src=etc/yum.repos.d/weblounge.repo.j2
        dest=/etc/yum.repos.d/weblounge.repo
        backup=yes
  tags: weblounge_repo


- name: "Installing Weblounge"
  yum: >
        name=weblounge
        state=latest
  notify:
        - restart weblounge
  tags: weblounge


- name: "Installing Apache webserver"
  yum: >
        name=httpd
        state=latest
  notify:
        - restart httpd
  tags: httpd


- name: "Configuring Apache for Weblounge proxying"
  template: >
        src=etc/httpd/conf.d/weblounge.conf.j2
        dest=/etc/httpd/conf.d/weblounge.conf
        backup=yes
  notify:
        - restart httpd
  tags: httpd


- name: "Creating Apache log files"
  file: >
        dest=/var/log/httpd/vhosts/${ansible_hostname}
        state=directory

- name: "Permanently starting Apache"
  service: >
        name=httpd
        state=started
        enabled=yes
  tags: httpd


- name: "Installing Image Magick"
  yum: >
        name=ImageMagick
        state=latest
  notify:
        - restart weblounge
  tags: imagemagick


- name: "Installing Phantomjs"
  yum: >
        name=phantomjs
        state=latest
  notify:
        - restart weblounge
  tags: pahntomjs


- name: "Configuring Weblounge node name"
  template: >
        src=etc/weblounge/config.properties.j2
        dest=/etc/weblounge/config.properties
        backup=yes
  notify:
        - restart weblounge
  tags: datasource


- name: "Creating directory for Weblounge database connection"
  file: >
        dest=/etc/weblounge/datasource
        state=directory
  notify:
        - restart weblounge
  tags: datasource


- name: "Configuring the Weblounge database connection"
  template: >
        src=etc/weblounge/datasource/weblounge-ds.xml.j2
        dest=/etc/weblounge/datasource/weblounge-ds.xml
        backup=yes
  notify:
        - restart weblounge
  tags: datasource


- name: "Configuring the Elasticsearch index"
  template: >
        src=etc/weblounge/index/settings.yml.j2
        dest=/etc/weblounge/index/settings.yml
        backup=yes
  notify:
        - restart weblounge
  tags: elasticsearch


- name: "Processing /etc/weblounge/weblounge.conf"
  template: >
        src=etc/weblounge/weblounge.conf.j2
        dest=/etc/weblounge/weblounge.conf
        backup=yes
  notify:
        - restart weblounge
  tags: service


- name: "Create the weblounge system user"
  user: >
        name=${weblounge_user}
        state=present
  tags: user
  notify:
        - restart weblounge


- name: "Create the weblounge system group"
  group: >
        name=${weblounge_group}
        state=present
        system=yes
  tags: group
  notify:
        - restart weblounge


- name: "Make the weblounge system user owner of the weblounge directories"
  file: >
        state=directory
        recurse=yes
        owner=${weblounge_user}
        path=$item
  with_items:
        - ${weblounge_cache_dir}
        - ${weblounge_temp_dir}
        - ${weblounge_log_dir}
        - ${weblounge_data_dir}
  tags: permissions
  notify:
        - restart weblounge


- name: "Installing Graylog library"
  copy: >
        src="/opt/weblounge/docs/scripts/ansible/nodes/roles/weblounge-common/files/gelfj-0.9.1.jar" 
        dest="/opt/weblounge/lib/local"
  tags: local-libs
  notify:
        - restart weblounge


- name: "Installing MySQL driver"
  copy: >
        src="/opt/weblounge/docs/scripts/ansible/nodes/roles/weblounge-common/files/mysql-connector-java-5.1.22.jar" 
        dest="/opt/weblounge/lib/local"
  tags: local-libs
  notify:
        - restart weblounge


- name: "Installing MySQL JPA datasource"
  copy: >
        src="/opt/weblounge/docs/scripts/ansible/nodes/roles/weblounge-common/files/pax-jdbc-mysql-0.2.0.jar" 
        dest="/opt/weblounge/lib/local"
  tags: local-libs
  notify:
        - restart weblounge


- name: "Enabling loading of local Java libraries"
  lineinfile: >
        dest="/etc/weblounge/system.properties"
        insertafter="mylibrary-1.0.0.jar"
        regexp="^felix\.auto\.start\.4"
        line="felix.auto.start.4= \\"
  tags: local-libs
  notify:
        - restart weblounge


- name: "Loading the local libraries"
  lineinfile: >
        dest="/etc/weblounge/system.properties"
        insertafter="^felix.auto.start.4"
        regexp="{{ item }}"
        line=" file:${weblounge.home}/lib/local/{{ item }} \\ "
  with_items:
        - "gelfj-0.9.1.jar "
        - "mysql-connector-java-5.1.22.jar "
        - "pax-jdbc-mysql-0.2.0.jar "
  tags: local-libs
  notify:
        - restart weblounge


- name: "Permanently starting Weblounge"
  service: >
        name=weblounge
        state=started
        enabled=yes
  tags: weblounge
